import { motion } from 'framer-motion';
import { Brain, FlaskConical, RefreshCw, Sparkles, Split, User } from 'lucide-react';
import { getAQILevel, aqiRGBA } from '../lib/aqiTheme';
import ReadAloudButton from './ReadAloudButton';
import ShareCard from './ShareCard';
import { AdvisorySkeleton } from './SkeletonLoader';
import { cn } from '../lib/utils';

/**
 * AdvisoryCard — the hero of the dashboard, restyled as the reference's
 * sidebar "history" card: a dotted vertical timeline of advisory points,
 * quiet status pills, dark glass surface.
 * Behavior is unchanged: staggered fade-in on every regeneration, source
 * badge (AI via Groq / smart rules), live vs what-if status, read-aloud,
 * share/export, manual regenerate.
 */

/** Parse advisory text into paragraphs and "• " action bullets. */
export function parseAdvisoryBlocks(text) {
  if (!text) return [];
  return text
    .split('\n')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((line) => ({
      kind: /^[•\-*–]\s+/.test(line) ? 'action' : 'para',
      text: line.replace(/^[•\-*–]\s+/, ''),
    }));
}

/** Staggered fade-in body — dotted timeline for action points, prose for
 *  paragraphs. Reused by the Compare view. */
export function AdvisoryBody({ text, accent = '#6c8cff' }) {
  const blocks = parseAdvisoryBlocks(text);
  return (
    <motion.div
      initial="hidden"
      animate="show"
      variants={{ hidden: {}, show: { transition: { staggerChildren: 0.12, delayChildren: 0.05 } } }}
      className="space-y-2.5"
      aria-live="polite"
    >
      {blocks.map((b, i) => (
        <motion.div
          key={i}
          variants={{
            hidden: { opacity: 0, y: 10 },
            show: { opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } },
          }}
        >
          {b.kind === 'action' ? (
            <div className="flex items-start gap-3">
              <span className="flex flex-col items-center self-stretch pt-[5px] shrink-0">
                <span
                  className="w-2.5 h-2.5 rounded-full border border-void shrink-0"
                  style={{ background: accent, boxShadow: `0 0 10px ${accent}66` }}
                />
                <span className="flex-1 w-px border-l border-dashed border-white/10 mt-1.5" aria-hidden="true" />
              </span>
              <p className="text-sm leading-relaxed text-muted">{b.text}</p>
            </div>
          ) : (
            <p className="text-sm leading-relaxed text-strong">{b.text}</p>
          )}
        </motion.div>
      ))}
    </motion.div>
  );
}

function SourceBadge({ source }) {
  const groq = source === 'groq';
  return (
    <span
      className={cn(
        'pill',
        groq
          ? 'bg-accent/10 border-accent/30 text-accent-soft'
          : 'bg-white/[0.05] border-white/[0.1] text-muted'
      )}
      title={groq ? 'Generated live by the Groq LLM' : 'Generated by the built-in smart-rules engine (no API key needed)'}
    >
      {groq ? <Brain className="w-3 h-3" /> : <Sparkles className="w-3 h-3" />}
      {groq ? 'AI · Groq' : 'Smart rules'}
    </span>
  );
}

export default function AdvisoryCard({
  advisory,
  loading,
  profile,
  conditions,
  onRegenerate,
  onOpenCompare,
}) {
  const level = getAQILevel(conditions?.aqi);

  return (
    <article
      className="glass rounded-2xl p-5 sm:p-6 flex flex-col gap-4 relative overflow-hidden"
      style={{
        borderTop: `3px solid ${level.color}`,
        boxShadow: conditions?.aqi != null ? `0 18px 50px -24px ${aqiRGBA(conditions.aqi, 0.45)}` : undefined,
      }}
      aria-label="Personalized health advisory"
    >
      {/* header chips */}
      <div className="flex items-center gap-2 flex-wrap">
        <Sparkles className="w-4 h-4 text-accent shrink-0" aria-hidden="true" />
        <h3 className="text-sm font-bold text-strong tracking-tight mr-1">Your advisory</h3>
        <span className="inline-flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-full bg-white/[0.04] border border-white/[0.08] text-muted max-w-full">
          <User className="w-3 h-3 shrink-0" aria-hidden="true" />
          <span className="truncate">{profile?.name || 'General Adult'}</span>
        </span>
        {advisory && <SourceBadge source={advisory.source} />}
        {conditions?.simulated && (
          <span className="pill bg-[#f2984c]/10 border-[#f2984c]/35 text-[#f2b06c]">
            <FlaskConical className="w-3 h-3" />
            What-if
          </span>
        )}
      </div>

      {/* body */}
      <div
        className={cn(
          'flex-1 transition-opacity min-h-[120px]',
          loading && advisory ? 'opacity-50 pointer-events-none' : 'opacity-100'
        )}
      >
        {loading && !advisory ? (
          <AdvisorySkeleton />
        ) : advisory ? (
          <AdvisoryBody key={`${advisory.generatedAt}-${advisory.source}`} text={advisory.text} accent={level.color} />
        ) : (
          <AdvisorySkeleton />
        )}
      </div>

      {/* actions */}
      <div className="border-t border-white/[0.06] pt-4 space-y-3">
        <div className="flex items-center gap-2 flex-wrap">
          <ReadAloudButton text={advisory?.text} disabled={!advisory || loading} />
          <button
            onClick={onRegenerate}
            disabled={loading || !conditions}
            className="inline-flex items-center gap-2 text-xs font-semibold px-3.5 py-2 rounded-full border bg-white/[0.04] border-white/[0.08] text-muted hover:text-accent-soft hover:border-accent/40 transition-colors disabled:opacity-40"
          >
            <RefreshCw className={cn('w-3.5 h-3.5', loading && 'animate-spin')} />
            Regenerate
          </button>
        </div>
        <ShareCard advisory={advisory} profile={profile} conditions={conditions} disabled={!advisory} />
      </div>

      {onOpenCompare && (
        <button
          onClick={onOpenCompare}
          className="self-start inline-flex items-center gap-1.5 text-xs font-semibold text-accent hover:text-accent-soft transition-colors"
        >
          <Split className="w-3.5 h-3.5" />
          See how advice changes for other profiles →
        </button>
      )}
    </article>
  );
}
